openapi: "3.0.0"
info:
  title: Tshirt store API
  description: Course to create Api
  version: 1.1.0
  contact: 
    email: subhamsourav175@gmail.com
    url: "https://lco.dev"

# servers:
#   - url: "https://localhost:4000/api/v1"
#     description: for local host - secure
#   - url: "https://localhost:4000/api/v1"
#     description: for local host - regural

servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: for local host - secure
    variables:
      version: 
        enum:
          - v1
          - v2
        default: v1
      protocol: 
        enum:
          - http
          - https
        default: http

components: 
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer   

paths:
  /dummy:
    get:
      tags: 
        - Home
      summary: returns a greet message from lco
      responses:
        200:
          description: All Good & success
          content:
            application/json:
              schema:
                type: string
                example: "My String"
        400:
          description: Bad Request
        500:
          description: Internal Server Error

